### ISSUE TITLE
Center toolbar title text

### ISSUE THREAD

**Issue by kuoliangkwong** [zendesk/android_sdk_demo_apps#36]
## Product
Which product does this affect? Add an 'x' in all that apply.
- [x] Support
- [x] Chat

## Problem
Which type of issue have you encountered? Add an 'x' in all that apply.
- [x] Demo app request
- [ ] Demo app broken
- [ ] Other

Is it possible to center toolbar title? Was trying to match to my app theme 

**Which feature would you like to see demonstrated?**
Center toolbar title 

**Which demo app has broken?**

## Reviewers
@zendesk/adventure-android @zendesk/two-brothers-android @zendesk/ogham @baz8080

**Comment by danthedrummer** [comment]
Hi, 
This isn't a styling option that we allow. It's possible in the Chat SDK but not in the Support SDK.

I pushed up a [branch](https://github.com/zendesk/android_sdk_demo_apps/tree/danthedrummer/toolbar-title-centering) demonstrating how to do it for Chat SDK

Feel free to make a feature request in our [community](https://develop.zendesk.com/hc/en-us/community/topics/360000018828-Mobile-SDKs) if you want more styling options.

Cheers,
Dan.

**Comment by danthedrummer** [comment]
Closing this issue as there has been no response for a while
