### ISSUE TITLE
Unread message count in android

### ISSUE THREAD

**Issue by Bhumik** [zendesk/android_sdk_demo_apps#38]
How to get unread message count in android?

I want to show badge in one of button of my activity. and do not want to use chat widget provided by sdk.
When user press button, I want to take him to chat screen.
Also if chat is initiated by agent.
In any case, if there is any unread message. I want to show count in my non chat screen.

**Comment by danthedrummer** [comment]
We don't provide an API to get the message count but you can observe the chat log and manage the counter yourself. Something like this:
```java
private int previousCount = 0;

ChatLogObserver chatLogObserver = new ChatLogObserver() {
    @Override
    public void update(LinkedHashMap<String, ChatLog> chatLog) {
        int currentCount = LivechatChatLogPath.getInstance().countMessages(ChatLog.Type.CHAT_MSG_AGENT);
        final int unread = currentCount - previousCount;
        if (unread > 0) {
            previousCount = currentCount;
            // update badge counter
        }
    }
};

@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.entry_activity);

    previousCount = LivechatChatLogPath.getInstance().countMessages(ChatLog.Type.CHAT_MSG_AGENT);
    ZopimChatApi.getDataSource().addChatLogObserver(chatLogObserver);
}
```

In future please fill out the Issue template

**Comment by danthedrummer** [comment]
Closing as there has been no response
