### ISSUE TITLE
How we can take this function on fragment?

### ISSUE THREAD

**Issue by chiragsharma991** [zendesk/android_sdk_demo_apps#40]
## Product
Which product does this affect? Add an 'x' in all that apply.
- [ ] Support
- [ ] Chat

## Problem
Which type of issue have you encountered? Add an 'x' in all that apply.
- [ ] Demo app request
- [ ] Demo app broken
- [x] Other

## Description

*Which feature would you like to see demonstrated?<br>
Which demo app has broken?*

## Reviewers
@zendesk/adventure-android @zendesk/two-brothers-android @zendesk/ogham @baz8080

**Comment by brendan-fahy** [comment]
Hi @chiragsharma991, can you add more detail? I'm not sure what you're asking for here.

**Comment by tecknut** [comment]
Hi @chiragsharma991 I'm going to close this due to inactivity.
