### ISSUE TITLE
Getting the result of a RequestActivity sent feedback

### ISSUE THREAD

**Issue by Dadoufi** [zendesk/android_sdk_demo_apps#41]
## Product
Which product does this affect? Add an 'x' in all that apply.
- [x] Support
- [ ] Chat

## Problem
Which type of issue have you encountered? Add an 'x' in all that apply.
- [ ] Demo app request
- [ ] Demo app broken
- [x] Other

## Description

Is there any way to get the result of the sent feedback in a RequestActivity?

In the previous version of the SDK(v1) it was possible to get the result by using startActivityForResult and then checking if the result code was RESULT_OK. 

While it's still possible to start the RequestActivity using startActivityForResult, the resultCode is always RESULT_CANCELED regardless of whether the feedback was successfully sent or not.

How i achieve the same result in the v2 SDK?

## Reviewers
@zendesk/adventure-android @zendesk/two-brothers-android @zendesk/ogham @baz8080

**Comment by danthedrummer** [comment]
Hi,
The supported way to start the `RequestActivity` is using it's builder as documented [here](https://developer.zendesk.com/embeddables/docs/android_support_sdk/requests#show-the-submit-ticket-screen), and we don't surface the result. You can create your own UI and handle the requests directly, or you can create a feature request in our [community](https://develop.zendesk.com/hc/en-us/community/topics/360000018828-Mobile-SDKs).
Cheers,
Dan.

**Comment by Dadoufi** [comment]
Thank you for the quick response, i will create a feature request.
