### ISSUE TITLE
Query Regarding anonymous Identity

### ISSUE THREAD

**Issue by akabirami** [zendesk/android_sdk_demo_apps#9]
Is this custom fields applicable only for JWT Identity or is it applicable also for anonymous Identity. I tried using the code for anonymous Identity but in 
RequestProvider provider=ZendeskConfig.INSTANCE.provider().requestProvider();
 it throws error like cannot resolve method provider(). Pls help with this

**Comment by baz8080** [comment]
@akabirami please ask this in our [forum](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs). You should also include how you installed the SDK (gradle / maven), and all relevant code snippets that will help us.
